sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: 192.168.152.100
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxb993cafedb87d00c
    secret: 4b5662ab93cd996dcc50c14ca5a21250
